"use client";
import { useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import Header from "../../../components/Header";
import Footer from "../../../components/Footer";
import { cn } from "../../../lib/utils";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Rogue",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  useEffect(() => {
    const body = document.querySelector("body");
    if (body) {
      body.classList.add(inter.className);
    }
  }, []);

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <Header />
      <main
        className={cn("min-h-screen flex flex-col")}
        style={{
          backgroundImage: `url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c0236e8e-8042-4ee1-8dd6-c64bb219d5be/dg45lbq-e3be588a-a058-4b95-96f2-43487e5afc08.png/v1/fill/w_1920,h_1280,q_80,strp/dnd__faerun_streets__by_bergionstyle_dg45lbq-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcL2MwMjM2ZThlLTgwNDItNGVlMS04ZGQ2LWM2NGJiMjE5ZDViZVwvZGc0NWxicS1lM2JlNTg4YS1hMDU4LTRiOTUtOTZmMi00MzQ4N2U1YWZjMDgucG5nIiwid2lkdGgiOiI8PTE5MjAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.bh0B6AWCtJxk5wr6Fk9EcUjZYuP-QoCCafSokY8h34w')`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        {children}
      </main>
      <Footer />
    </>
  );
}
