import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "../../../components/Header";
import Footer from "../../../components/Footer";
import { cn } from "../../../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bard",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={cn(
          inter.className,
          "min-h-screen flex flex-col bg-purple-200"
        )}
      >
        <Header />
        <main className="flex-1 p-4 flex flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
