"use client";
import { useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import Header from "../../../components/Header";
import Footer from "../../../components/Footer";
import { cn } from "../../../lib/utils";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Warrior",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  useEffect(() => {
    const body = document.querySelector("body");
    if (body) {
      body.classList.add(inter.className);
    }
  }, []);

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <Header />
      <main
        className={cn("min-h-screen flex flex-col")}
        style={{
          backgroundImage: `url('https://cdna.artstation.com/p/assets/images/images/028/288/940/large/diego-herrera-sosa-previo-17-final.jpg?1594049355')`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        {children}
      </main>
      <Footer />
    </>
  );
}
